### ISSUE TITLE
请问有原始数据吗

### ISSUE THREAD

**Issue by znnnnn1** [iqgnat/SSVEP_phase_latency#1]

**Comment by iqgnat** [comment]
清华官方有SSVEP的公开数据集。

**Comment by znnnnn1** [comment]
可以给个链接吗，不确定是哪个，麻烦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iqgnat/SSVEP_phase_latency"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月1日(星期天) 中午1:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iqgnat/SSVEP_phase_latency] 请问有原始数据吗 (#1)





 
清华官方有SSVEP的公开数据集。

**Comment by iqgnat** [comment]
https://ieeexplore.ieee.org/abstract/document/7740878?casa_token=mecbGC1rQeoAAAAA:RDk2cohOOyT6w0WC6J0pFH5w7fSEcBsYW0i_OVdzG6PH2Agy8jEm3mRfnoKU5XowaiRwGaGhFuA

**Comment by znnnnn1** [comment]
太感谢您了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iqgnat/SSVEP_phase_latency"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月2日(星期一) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [iqgnat/SSVEP_phase_latency] 请问有原始数据吗 (#1)





 
https://ieeexplore.ieee.org/abstract/document/7740878?casa_token=mecbGC1rQeoAAAAA:RDk2cohOOyT6w0WC6J0pFH5w7fSEcBsYW0i_OVdzG6PH2Agy8jEm3mRfnoKU5XowaiRwGaGhFuA

**Comment by iqgnat** [comment]
客气了~
